package com.softdesign.devintensive.utils;

public interface ConstantManager {
    String TAG_PREFIX = "DEV ";

    String EDIT_MODE_KEY = "EDIT_MODE_KEY";

    String USER_PHONE_KEY = "USER_PHONE_KEY";
    String USER_EMAIL_KEY = "USER_EMAIL_KEY";
    String USER_VK_KEY = "USER_VK_KEY";
    String USER_GIT_KEY = "USER_GIT_KEY";
    String USER_BIO_KEY = "USER_BIO_KEY";
    String USER_NAME_KEY = "USER_NAME_KEY";
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";
    String USER_AVATAR_KEY = "USER_AVATAR_KEY";
    String USER_ID_KEY = "USER_ID_KEY";
    String AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";
    String USER_RATING_VALUE = "USER_RATING_VALUE";
    String USER_CODE_LINES_VALUE = "USER_CODE_LINES_VALUE";
    String USER_PROJECT_VALUE = "USER_PROJECT_VALUE";
    String USER_LOGIN_EMAIL = "USER_LOGIN_EMAIL";

    String PARCELABLE_KEY = "PARCELABLE_KEY";
    String RETAINED_FRAGMENT_KEY = "RETAINED_FRAGMENT_KEY";
    String SAVED_STATE_KEY = "SAVED_STATE_KEY";

    String START_PROFILE_ACTIVITY_KEY = "START_PROFILE_ACTIVITY_KEY";
    String LIKE_USER_KEY = "LIKE_USER_KEY";
    String UNLIKE_USER_KEY = "UNLIKE_USER_KEY";

    int LOAD_PROFILE_PHOTO = 1;
    int LOAD_PROFILE_AVATAR = 2;
    int REQUEST_CAMERA_PHOTO = 100;
    int REQUEST_GALLERY_PHOTO = 101;
    int REQUEST_CAMERA_AVATAR = 102;

    int REQUEST_GALLERY_AVATAR = 103;
    int PERMISSION_REQUEST_SETTINGS_CODE = 200;
    int CAMERA_PERMISSION_REQUEST_CODE = 201;
    int SEARCH_DELAY = 2000;
}